### ISSUE TITLE
Compiling the feature/staticSDE branch

### ISSUE THREAD

**Issue by BlockCat** [mrdepth/libdgmpp#4]
Hello,

I'm trying to compile the feature/staticSDE branch, but I seem to get errors.
How do I compile this?

**Comment by mrdepth** [comment]
1. Configure your project settings to use C++17 compiler.
2. Add sources from "./src" folder to the project. You may need add -I compiler flag to the ./src/SDE subfolder.
3. Include "dgmpp.hpp"

You can also use SWIG interface to build wrappers for other languages.

**Comment by BlockCat** [comment]
Hello,

As soon as I woke up I realized that I stated the absolute minimum to work with.
I use a c++17 compiler (gcc-7) and have added all the sources. The errors I get however are conflicting declarations and undeclared classes.
`gcc-7 -std=c++1z main.cpp  -I.. -I. -I./SDE`
`
In file included from ./MetaInfo.hpp:9:0,
                 from ./Type.hpp:9,
                 from ./Skill.hpp:9,
                 from ./Character.hpp:9,
                 from ./Gang.hpp:9,
                 from dgmpp.hpp:8,
                 from main.cpp:2:
./Utility.hpp:33:49: error: conflicting declaration of template ‘template<class T> using optional = std::experimental::fundamentals_v1::optional<_Tp>’
  using optional = std::experimental::optional<T>;
                                                 ^
In file included from /usr/include/c++/7/bits/node_handle.h:39:0,
                 from /usr/include/c++/7/bits/stl_tree.h:72,
                 from /usr/include/c++/7/set:60,
                 from ./Utility.hpp:12,
                 from ./MetaInfo.hpp:9,
                 from ./Type.hpp:9,
                 from ./Skill.hpp:9,
                 from ./Character.hpp:9,
                 from ./Gang.hpp:9,
                 from dgmpp.hpp:8,
                 from main.cpp:2:
/usr/include/c++/7/optional:55:11: note: previous declaration ‘template<class _Tp> class std::optional’
     class optional;
           ^~~~~~~~
In file included from ./MetaInfo.hpp:9:0,
                 from ./Type.hpp:9,
                 from ./Skill.hpp:9,
                 from ./Character.hpp:9,
                 from ./Gang.hpp:9,
                 from dgmpp.hpp:8,
                 from main.cpp:2:
./Utility.hpp:34:17: error: conflicting declaration ‘constexpr const auto std::nullopt’
  constexpr auto nullopt = std::experimental::nullopt;
                 ^~~~~~~
In file included from /usr/include/c++/7/bits/node_handle.h:39:0,
                 from /usr/include/c++/7/bits/stl_tree.h:72,
                 from /usr/include/c++/7/set:60,
                 from ./Utility.hpp:12,
                 from ./MetaInfo.hpp:9,
                 from ./Type.hpp:9,
                 from ./Skill.hpp:9,
                 from ./Character.hpp:9,
                 from ./Gang.hpp:9,
                 from dgmpp.hpp:8,
                 from main.cpp:2:
/usr/include/c++/7/optional:72:30: note: previous declaration as ‘constexpr const std::nullopt_t std::nullopt’
   inline constexpr nullopt_t nullopt { nullopt_t::_Construct::_Token };
                              ^~~~~~~
In file included from ./MetaInfo.hpp:9:0,
                 from ./Type.hpp:9,
                 from ./Skill.hpp:9,
                 from ./Character.hpp:9,
                 from ./Gang.hpp:9,
                 from dgmpp.hpp:8,
                 from main.cpp:2:
./Utility.hpp:47:20: error: ‘Float’ does not name a type
  using GigaJoule = Float;
                    ^~~~~
./Utility.hpp:48:20: error: ‘Float’ does not name a type
  using Teraflops = Float;
                    ^~~~~
./Utility.hpp:49:20: error: ‘Float’ does not name a type
  using MegaWatts = Float;
                    ^~~~~
./Utility.hpp:50:28: error: ‘Float’ does not name a type
  using CalibrationPoints = Float;
                            ^~~~~
./Utility.hpp:52:21: error: ‘Float’ does not name a type
  using CubicMeter = Float;
                     ^~~~~
./Utility.hpp:53:16: error: ‘Float’ does not name a type
  using Meter = Float;
                ^~~~~
./Utility.hpp:54:21: error: ‘Float’ does not name a type
  using Millimeter = Float;
                     ^~~~~
./Utility.hpp:55:28: error: ‘Float’ does not name a type
  using MegabitsPerSecond = Float;
                            ^~~~~
./Utility.hpp:56:19: error: ‘Float’ does not name a type
  using Kilogram = Float;
                   ^~~~~
./Utility.hpp:57:17: error: ‘Float’ does not name a type
  using Points = Float;
                 ^~~~~
./Utility.hpp:58:13: error: ‘Float’ does not name a type
  using HP = Float;
             ^~~~~
./Utility.hpp:59:18: error: ‘Float’ does not name a type
  using Radians = Float;
                  ^~~~~
./Utility.hpp:60:27: error: ‘Float’ does not name a type
  using AstronomicalUnit = Float;
                           ^~~~~
./Utility.hpp:61:18: error: ‘Float’ does not name a type
  using Percent = Float;
                  ^~~~~
./Utility.hpp:62:21: error: ‘Float’ does not name a type
  using Multiplier = Float;
                     ^~~~~
./Utility.hpp:63:29: error: ‘rate’ does not name a type
  using GigaJoulePerSecond = rate<GigaJoule, std::chrono::seconds>;
                             ^~~~
./Utility.hpp:64:30: error: ‘rate’ does not name a type
  using CubicMeterPerSecond = rate<CubicMeter, std::chrono::seconds>;
                              ^~~~
./Utility.hpp:65:28: error: ‘rate’ does not name a type
  using RadiansPerSecond  = rate<Radians, std::chrono::seconds>;
                            ^~~~
./Utility.hpp:66:27: error: ‘rate’ does not name a type
  using MetersPerSecond  = rate<Meter, std::chrono::seconds>;
                           ^~~~
./Utility.hpp:67:37: error: ‘rate’ does not name a type
  using AstronomicalUnitsPerSecond = rate<Meter, std::chrono::seconds>;
                                     ^~~~
./Utility.hpp:68:22: error: ‘rate’ does not name a type
  using HPPerSecond = rate<HP, std::chrono::seconds>;
                      ^~~~
./Utility.hpp:71:9: error: ‘Percent’ does not name a type
   const Percent capacitorPeakRecharge = 0.5; //sqrt(0.25)
         ^~~~~~~
./Utility.hpp:72:9: error: ‘Percent’ does not name a type
   const Percent shieldPeakRecharge = 0.5; //sqrt(0.25)
         ^~~~~~~
........................
In file included from dgmpp.hpp:12:0,
                 from main.cpp:2:
./Factory.hpp:32:29: error: template argument 1 is invalid
   std::list<std::unique_ptr<ProductionCycle>> cycles_;
                             ^~~~~~~~~~~~~~~
./Factory.hpp:32:29: error: template argument 2 is invalid
./Factory.hpp:32:44: error: template argument 1 is invalid
   std::list<std::unique_ptr<ProductionCycle>> cycles_;
                                            ^~
./Factory.hpp:32:44: error: template argument 2 is invalid
./Factory.hpp:34:9: error: ‘Facility’ has not been declared
   using Facility::Facility;
         ^~~~~~~~
./Factory.hpp:40:16: error: conflicting declaration ‘struct dgmpp::Planet’
   friend class Planet;
                ^~~~~~
In file included from ./Planet.hpp:9:0,
                 from dgmpp.hpp:9,
                 from main.cpp:2:
./Facility.hpp:15:8: note: previous declaration as ‘class dgmpp::Planet’
  class Planet;
        ^~~~~~
In file included from dgmpp.hpp:12:0,
                 from main.cpp:2:
./Factory.hpp:40:3: error: friend declaration does not name a class or function
   friend class Planet;
   ^~~~~~
./Factory.hpp:41:9: error: ‘MetaInfo’ does not name a type
   const MetaInfo::Schematic* schematic_ = nullptr;
         ^~~~~~~~
./Factory.hpp:48:3: error: ‘ProductionCycle’ does not name a type
   ProductionCycle* production_ = nullptr;
   ^~~~~~~~~~~~~~~
./Factory.hpp:50:24: error: ‘MetaInfo’ does not name a type
   void schematic(const MetaInfo::Schematic* schematic) noexcept { schematic_ = schematic; }
                        ^~~~~~~~
./Factory.hpp:50:43: error: expected unqualified-id before ‘*’ token
   void schematic(const MetaInfo::Schematic* schematic) noexcept { schematic_ = schematic; }
                                           ^
./Factory.hpp:50:43: error: expected ‘)’ before ‘*’ token
./Factory.hpp:50:34: error: expected ‘;’ at end of member declaration
   void schematic(const MetaInfo::Schematic* schematic) noexcept { schematic_ = schematic; }
                                  ^~~~~~~~~
./Factory.hpp:50:45: error: ISO C++ forbids declaration of ‘schematic’ with no type [-fpermissive]
   void schematic(const MetaInfo::Schematic* schematic) noexcept { schematic_ = schematic; }
                                             ^~~~~~~~~
./Factory.hpp:50:45: error: expected ‘;’ at end of member declaration
./Factory.hpp:50:45: error: ‘int* dgmpp::Factory::schematic’ conflicts with a previous declaration
./Factory.hpp:50:8: note: previous declaration ‘dgmpp::Factory::schematic’
   void schematic(const MetaInfo::Schematic* schematic) noexcept { schematic_ = schematic; }
        ^~~~~~~~~
./Factory.hpp:50:54: error: expected unqualified-id before ‘)’ token
   void schematic(const MetaInfo::Schematic* schematic) noexcept { schematic_ = schematic; }
                                                      ^
./Factory.hpp:51:20: error: ‘ProductionCycle’ has not been declared
   void finishCycle(ProductionCycle& cycle, std::chrono::seconds time);
                    ^~~~~~~~~~~~~~~
./Factory.hpp:52:3: error: ‘ProductionCycle’ does not name a type
   ProductionCycle* startCycle(std::chrono::seconds time);
   ^~~~~~~~~~~~~~~
./Factory.hpp:15:16: error: ‘virtual bool dgmpp::Factory::configured() const’ marked ‘override’, but does not override
   virtual bool configured() const override;
                ^~~~~~~~~~
./Factory.hpp:35:47: error: ‘virtual std::optional<std::chrono::duration<long int> > dgmpp::Factory::nextUpdateTime() const’ marked ‘override’, but does not override
   virtual std::optional<std::chrono::seconds> nextUpdateTime() const noexcept override;
                                               ^~~~~~~~~~~~~~
./Factory.hpp:36:15: error: ‘virtual int dgmpp::Factory::priority() const’ marked ‘override’, but does not override
   virtual int priority() const noexcept override;
               ^~~~~~~~
./Factory.hpp:37:16: error: ‘virtual void dgmpp::Factory::update(std::chrono::seconds)’ marked ‘override’, but does not override
   virtual void update(std::chrono::seconds time) override;
                ^~~~~~
In file included from dgmpp.hpp:13:0,
                 from main.cpp:2:
./Spaceport.hpp:13:34: error: expected class-name before ‘{’ token
  class Spaceport: public Storage {
                                  ^
./Spaceport.hpp:16:9: error: ‘Storage’ has not been declared
   using Storage::Storage;
         ^~~~~~~
./Spaceport.hpp:18:16: error: conflicting declaration ‘struct dgmpp::Planet’
   friend class Planet;
                ^~~~~~
In file included from ./Planet.hpp:9:0,
                 from dgmpp.hpp:9,
                 from main.cpp:2:
./Facility.hpp:15:8: note: previous declaration as ‘class dgmpp::Planet’
  class Planet;
        ^~~~~~
In file included from dgmpp.hpp:13:0,
                 from main.cpp:2:
./Spaceport.hpp:18:3: error: friend declaration does not name a class or function
   friend class Planet;
   ^~~~~~
main.cpp: In function ‘int std::main(int, const char**)’:
main.cpp:8:21: error: ‘class dgmpp::Gang’ has no member named ‘addPilot’
  auto pilot = gang->addPilot();
                     ^~~~~~~~
main.cpp:12:29: error: ‘dgmpp::Module’ has not been declared
  auto ab = ship->add(dgmpp::Module::Create(TypeID::_100MNAfterburnerII));
                             ^~~~~~
main.cpp:13:19: error: ‘dgmpp::Module’ has not been declared
  ab->state(dgmpp::Module::State::overloaded);
`

My first thoughts are that #pragma once declarations are not working, but it is said that gcc does actually support these.

Compiling with `gcc-7 -std=c++1z main.cpp  -I.. -I. -I./SDE -MM` gives `main.o: main.cpp dgmpp.hpp Gang.hpp Character.hpp Skill.hpp Type.hpp \
 MetaInfo.hpp Utility.hpp AttributeID.hpp CategoryID.hpp GroupID.hpp \
 TypeID.hpp EffectID.hpp WarfareBuffID.hpp Rate.hpp SchematicID.hpp \
 Attribute.hpp Effect.hpp Modifier.hpp WarfareBuff.hpp Structure.hpp \
 Ship.hpp Module.hpp Charge.hpp DamageVector.hpp Drone.hpp Capacitor.hpp \
 Tank.hpp HitPoints.hpp Area.hpp HeatSimulator.hpp Implant.hpp \
 Booster.hpp Planet.hpp Facility.hpp Route.hpp Commodity.hpp Errors.hpp \
 ProductionState.hpp ProductionCycle.hpp CommandCenter.hpp Storage.hpp \
 ExtractorControlUnit.hpp Factory.hpp Spaceport.hpp` so all header files included.

**Comment by mrdepth** [comment]
Please make a pull and try again.

**Comment by BlockCat** [comment]
This fix did indeed fix a lot of errors.

After that I got that `Type.hpp` is missing the `<functional>` include. (Added it to to `Utility.hpp`)
```
Tank.hpp:24:17: error: member ‘dgmpp::HPPerSecond dgmpp::Tank::<unnamed union>::<unnamed struct>::passiveShield’ with constructor not allowed in anonymous aggregate
```
After removing the union, I got:
```
ExtractorControlUnit.hpp:26:97: error: ‘pow’ is not a member of ‘std’
   void quantityPerCycle (size_t value) noexcept { quantityPerCycle_ = value; phaseShift_ = std::pow(value, 0.7); }
```
So I included `<cmath>` to `Utility.hpp`

After that it worked.
Should I make a fork for these changes?

**Comment by mrdepth** [comment]
Thank you. I made myself this changes. Can you try again?

**Comment by BlockCat** [comment]
Yes, compiling completely works.

I do get warnings like below, but they can be ignored.
```
Utility.hpp:131:33: warning: changes meaning of ‘slice’ from ‘class dgmpp::slice<std::_Rb_tree_const_iterator<std::tuple<dgmpp::Module::Slot, int, std::unique_ptr<dgmpp::Module, std::default_delete<dgmpp::Module> > > > >’ [-fpermissive]
  template <typename Iter> class slice {
```
